import {
  FiHome,
  FiUser,
  FiEdit,
  FiPlusCircle,
  FiSave,
  FiX,
  FiMoreVertical,
  FiTrash,
  FiMoon,
  FiSun,
  FiMonitor,
  FiCopy,
  FiGrid,
  FiList,
  FiHelpCircle,
  FiActivity,
  FiSettings,
  FiAlignJustify,
  FiChevronDown,
  FiSunrise,
  FiCalendar,
  FiAward,
  FiCheckCircle,
} from 'react-icons/fi';

import { RiDraggable } from 'react-icons/ri';

const icons = {
  Home: FiHome,
  User: FiUser,
  Edit: FiEdit,
  PlusCircle: FiPlusCircle,
  Save: FiSave,
  X: FiX,
  MoreVertical: FiMoreVertical,
  Trash: FiTrash,
  Moon: FiMoon,
  Sun: FiSun,
  Monitor: FiMonitor,
  Draggable: RiDraggable,
  Copy: FiCopy,
  Grid: FiGrid,
  List: FiList,
  Help: FiHelpCircle,
  Sunrise: FiSunrise,
  Activity: FiActivity,
  Calendar: FiCalendar,
  Settings: FiSettings,
  AlignJustify: FiAlignJustify,
  ChevronDown: FiChevronDown,
  Award: FiAward,
  CheckCircle: FiCheckCircle,
};

export default icons;
