export const routes = {
  home: '/',
  profile: '/profile',
  login: '/login',
  register: '/register',
  search: '/search',
  filter: '/filter',
  movies: '/movies',
  shows: '/shows',
  genre: '/genre',
  cartoons: '/cartoons',
  series: '/series',
  setting: 'profile/settings',
  favorites: 'profile/favorites',
  admin: 'profile/admin',
};
